FROM openjdk:11

# Set the working directory inside the container
COPY . /usr
WORKDIR /usr

# Command to run the application when the container starts
CMD ["java", "-jar", "target/jdbc-1.0-SNAPSHOT.jar"]

